name: Generate Trailer Views
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Trailer Viewer Generator
        uses: Georges034302/trailer-viewer-generator@main
        with:
          email: ${{ secrets.GITHUB_ACTOR }}@localhost
          name: ${{ secrets.GITHUB_ACTOR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
